# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  #https加密端口为443
  port: 443
  servlet:
    path: /
  #配置SSL证书
  ssl:
    key-store: classpath:server.jks
    key-store-password: Mz8&rA&Xco!Kc&Pg
    keyStoreType: jks

spring:
  profiles:
    # 环境 dev|test|pro
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: eschool-wechat
  mvc:
    throw-exception-if-no-handler-found: true
  #    static-path-pattern: /resources/**
  #    prefer-ip-address: true
  resources:
    static-locations: classpath:/static/

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  #mapper文件配置
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    #驼峰法
    map-underscore-to-camel-case: true
    cache-enabled: false
    #别名设置
  type-aliases-package: com.eschool.**.**.entity

weixin:
  appId: wx7d866d433aa31957
  appSecret: a372bb8c388c50603e147082e0997905

